# Generated by Django 3.0.1 on 2019-12-22 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0013_auto_20191222_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='relation',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2019, 12, 22, 13, 9, 36, 755551)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2019, 12, 22, 13, 9, 36, 742412)),
        ),
    ]
