# Generated by Django 2.2.6 on 2019-10-13 21:00

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catType',
            field=models.CharField(db_index=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='category',
            name='citySite',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(db_index=True, max_length=5), default=list, size=None),
        ),
        migrations.AddField(
            model_name='category',
            name='deliveryType',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='category',
            name='pickType',
            field=models.CharField(default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='category',
            name='postCompleteEnable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='completeType',
            field=models.CharField(default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='deliveryType',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='item',
            name='heading',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='inspection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='pickType',
            field=models.CharField(default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='variant',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
