# Generated by Django 2.2.6 on 2019-10-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0003_auto_20191013_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='postComplete',
            field=models.BooleanField(default=False),
        ),
    ]
