# Generated by Django 3.0.1 on 2020-02-21 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='unique_id',
            new_name='coordinates_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2020, 2, 21, 19, 39, 46, 616173)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2020, 2, 21, 19, 39, 46, 603570)),
        ),
    ]
