# Generated by Django 3.0.1 on 2019-12-18 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='device_token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2019, 12, 18, 18, 52, 18, 487656)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2019, 12, 18, 18, 52, 18, 474744)),
        ),
    ]
