# Generated by Django 3.0.1 on 2020-04-26 10:42

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('gender', models.CharField(default='', max_length=10)),
                ('address', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('coordinates_id', models.CharField(db_index=True, default='', max_length=50)),
                ('dob', models.DateField(default=datetime.datetime(2020, 4, 26, 10, 42, 23, 376706, tzinfo=utc))),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(db_index=True, default='', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('servei_cluster', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('servei_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), default=list, size=None)),
                ('accepted_items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), default=list, size=None)),
                ('picked_items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), default=list, size=None)),
                ('pick_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), default=list, size=None)),
                ('final_servei_cluster', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('net_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('extra_charges', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('status', models.IntegerField(default=0)),
                ('time_log', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('pilot_cluster', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('position', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0, srid=4326), srid=4326)),
                ('customer_id', models.CharField(db_index=True, default='', max_length=15)),
                ('customer_stack', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('date_time_creation', models.DateTimeField(default=datetime.datetime(2020, 4, 26, 10, 42, 23, 351176, tzinfo=utc))),
                ('payment_complete', models.BooleanField(default=False)),
                ('payment_COD', models.BooleanField(default=True)),
                ('payment_id', models.TextField(default='')),
                ('payment_stack', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('delivery_type', models.CharField(default='', max_length=3)),
                ('cityCode', models.CharField(default='', max_length=8)),
                ('otp', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 4, 26, 10, 42, 23, 308506, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lociestoresite',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2020, 4, 26, 10, 42, 23, 397804, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lociestoresite',
            name='last_settlement_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 10, 42, 23, 397570, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default=datetime.time(10, 42, 23, 343440)),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default=datetime.time(10, 42, 23, 343236)),
        ),
    ]
