# Generated by Django 3.0.1 on 2019-12-19 12:27

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0002_auto_20191218_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCode',
            fields=[
                ('city', models.CharField(db_index=True, default='', max_length=40)),
                ('cityCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('state', models.CharField(db_index=True, default='', max_length=20)),
                ('pin_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(db_index=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='account',
            name='relation',
            field=models.CharField(db_index=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_applied',
            field=models.DateField(default=datetime.date(2019, 12, 19)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2019, 12, 19, 12, 27, 1, 918534)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2019, 12, 19, 12, 27, 1, 894691)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='dob',
            field=models.DateField(default=datetime.date(2019, 12, 19)),
        ),
    ]
