# Generated by Django 3.0.1 on 2020-04-01 20:52

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0002_auto_20200401_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultitems',
            name='required_desc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.time(20, 52, 27, 486179)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_of_creation',
            field=models.TimeField(default=datetime.time(20, 52, 27, 486115)),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default=datetime.time(20, 52, 27, 479258)),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default=datetime.time(20, 52, 27, 479153)),
        ),
    ]
