# Generated by Django 3.0.1 on 2020-04-28 14:38

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0002_auto_20200426_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickDropOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_phone_number', models.CharField(db_index=True, default='', max_length=13)),
                ('sender_address', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('sender_name', models.CharField(default='', max_length=70)),
                ('receivers_stack', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('payee', models.CharField(default='SEN', max_length=3)),
                ('distance', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 14, 38, 55, 670468, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 14, 38, 55, 702826, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lociestoresite',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 14, 38, 55, 712663, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lociestoresite',
            name='last_settlement_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 14, 38, 55, 712548, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 14, 38, 55, 690468, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.date(2020, 4, 28)),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default=datetime.time(14, 38, 55, 686733)),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default=datetime.time(14, 38, 55, 686628)),
        ),
    ]
