# Generated by Django 3.0.1 on 2020-04-03 21:59

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0003_auto_20200401_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='account',
            name='data_joined',
            field=models.DateField(default=datetime.date(2020, 4, 3)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.date(2020, 4, 3)),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_applied',
            field=models.DateField(default=datetime.date(2020, 4, 3)),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_requested',
            field=models.DateField(default=datetime.date(2020, 4, 3)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2020, 4, 3)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.time(21, 59, 53, 47111)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_of_creation',
            field=models.TimeField(default=datetime.time(21, 59, 53, 47050)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.date(2020, 4, 3)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='dob',
            field=models.DateField(default=datetime.date(2020, 4, 3)),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default=datetime.time(21, 59, 53, 39947)),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default=datetime.time(21, 59, 53, 39829)),
        ),
    ]
