# Generated by Django 3.0.1 on 2020-02-21 19:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0003_auto_20200221_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2020, 2, 21, 19, 53, 17, 144053)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='coordinates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locie.Coordinates'),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2020, 2, 21, 19, 53, 17, 132898)),
        ),
    ]
