# Generated by Django 3.0.1 on 2019-12-20 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0003_auto_20191219_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPLog',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data', models.CharField(default='', max_length=6)),
                ('phone_number', models.CharField(db_index=True, default='', max_length=12)),
                ('otp_cred', models.CharField(default='', max_length=40, primary_key=True, serialize=False)),
                ('closed', models.BooleanField(default=False)),
                ('closing', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(db_index=True, default='', max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='phone_token',
            field=models.CharField(db_index=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_applied',
            field=models.DateField(default=datetime.date(2019, 12, 20)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2019, 12, 20, 19, 9, 43, 576516)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2019, 12, 20, 19, 9, 43, 527807)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='dob',
            field=models.DateField(default=datetime.date(2019, 12, 20)),
        ),
    ]
