# Generated by Django 3.0.1 on 2020-02-21 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0004_auto_20200221_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servei',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='servei',
            name='coordinates_id',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2020, 2, 21, 20, 5, 24, 711114)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2020, 2, 21, 20, 5, 24, 700133)),
        ),
    ]
