# Generated by Django 3.0.1 on 2020-04-04 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0004_auto_20200403_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='data_joined',
            field=models.DateField(default=datetime.date(2020, 4, 4)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.date(2020, 4, 4)),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_applied',
            field=models.DateField(default=datetime.date(2020, 4, 4)),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_requested',
            field=models.DateField(default=datetime.date(2020, 4, 4)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2020, 4, 4)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.time(16, 52, 19, 461015)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_of_creation',
            field=models.TimeField(default=datetime.time(16, 52, 19, 460951)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.date(2020, 4, 4)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='dob',
            field=models.DateField(default=datetime.date(2020, 4, 4)),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default=datetime.time(16, 52, 19, 453787)),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default=datetime.time(16, 52, 19, 453685)),
        ),
    ]
