# Generated by Django 3.0.1 on 2019-12-20 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0004_auto_20191220_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2019, 12, 20, 19, 24, 35, 258557)),
        ),
        migrations.AlterField(
            model_name='otplog',
            name='closing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2019, 12, 20, 19, 24, 35, 244482)),
        ),
    ]
