# Generated by Django 3.0.1 on 2020-02-21 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0005_auto_20200221_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='pilot',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='store',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='customer',
            name='coordinates_id',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pilot',
            name='coordinates_id',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='coordinates_id',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2020, 2, 21, 20, 31, 40, 778859)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2020, 2, 21, 20, 31, 40, 699061)),
        ),
    ]
