# Generated by Django 3.0.1 on 2020-05-05 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0005_auto_20200504_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 10, 52, 4, 233169, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 10, 52, 4, 266660, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerreviewmodel',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 10, 52, 4, 282315, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lociestoresite',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 10, 52, 4, 276190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 10, 52, 4, 254397, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publytics',
            name='start_dates',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 10, 52, 4, 280156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.date(2020, 5, 5)),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default=datetime.time(10, 52, 4, 250439)),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default=datetime.time(10, 52, 4, 250327)),
        ),
    ]
