# Generated by Django 3.0.1 on 2019-12-21 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0005_auto_20191220_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_token',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_applied',
            field=models.DateField(default=datetime.date(2019, 12, 21)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2019, 12, 21, 12, 53, 1, 705111)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2019, 12, 21, 12, 53, 1, 692390)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='dob',
            field=models.DateField(default=datetime.date(2019, 12, 21)),
        ),
    ]
