# Generated by Django 3.0.1 on 2020-05-05 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0006_auto_20200505_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickdroporder',
            name='droped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickdroporder',
            name='picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickdroporder',
            name='pilot_id',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 12, 5, 40, 318232, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 12, 5, 40, 385047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerreviewmodel',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 12, 5, 40, 399482, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lociestoresite',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 12, 5, 40, 394436, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 12, 5, 40, 372853, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publytics',
            name='start_dates',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 12, 5, 40, 397680, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default=datetime.time(12, 5, 40, 366945)),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default=datetime.time(12, 5, 40, 366753)),
        ),
    ]
