# Generated by Django 3.0.1 on 2020-02-21 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0006_auto_20200221_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2020, 2, 21, 21, 9, 44, 285645)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2020, 2, 21, 21, 9, 44, 264822)),
        ),
    ]
