# Generated by Django 3.0.1 on 2020-05-08 20:57

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0007_auto_20200505_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinates',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='accepted_items',
            new_name='droped_list',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pick_list',
            new_name='picked_list',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='picked_items',
            new_name='receivers_list',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='coordinates_id',
        ),
        migrations.RemoveField(
            model_name='pilot',
            name='coordinates_id',
        ),
        migrations.RemoveField(
            model_name='servei',
            name='coordinates_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='coordinates_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0, srid=4326), srid=4326),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='locie_reversion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='order',
            name='locie_transfer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='order',
            name='route_plan',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='order',
            name='senders_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), default=list, size=None),
        ),
        migrations.AddField(
            model_name='pilot',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0, srid=4326), srid=4326),
        ),
        migrations.AddField(
            model_name='servei',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0, srid=4326), srid=4326),
        ),
        migrations.AddField(
            model_name='store',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0, srid=4326), srid=4326),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 5, 8, 20, 57, 4, 235738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 5, 8, 20, 57, 4, 303674, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerreviewmodel',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 20, 57, 4, 335062, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lociestoresite',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2020, 5, 8, 20, 57, 4, 324400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 20, 57, 4, 277800, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publytics',
            name='start_dates',
            field=models.DateField(default=datetime.datetime(2020, 5, 8, 20, 57, 4, 331411, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.date(2020, 5, 8)),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default=datetime.time(20, 57, 4, 269030)),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default=datetime.time(20, 57, 4, 268816)),
        ),
    ]
