# Generated by Django 3.0.1 on 2020-04-04 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0007_auto_20200404_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.time(16, 56, 13, 721078)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_of_creation',
            field=models.TimeField(default=datetime.time(16, 56, 13, 721011)),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default=datetime.time(16, 56, 13, 713760)),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default=datetime.time(16, 56, 13, 713648)),
        ),
    ]
