# Generated by Django 3.0.1 on 2019-12-22 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0007_auto_20191222_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2019, 12, 22, 15, 15, 0, 585792)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2019, 12, 22, 15, 15, 0, 572438)),
        ),
    ]
