# Generated by Django 3.0.1 on 2020-03-14 22:02

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0008_auto_20200308_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='store',
            name='store_link',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='store_site_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='store_template',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='data_joined',
            field=models.DateField(default=datetime.date(2020, 3, 14)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.date(2020, 3, 14)),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_applied',
            field=models.DateField(default=datetime.date(2020, 3, 14)),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_requested',
            field=models.DateField(default=datetime.date(2020, 3, 14)),
        ),
        migrations.AlterField(
            model_name='ontonotfication',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 22, 1, 59, 478859, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2020, 3, 14)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.time(22, 1, 59, 468207)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_of_creation',
            field=models.TimeField(default=datetime.time(22, 1, 59, 468133)),
        ),
        migrations.AlterField(
            model_name='phonetoken',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 22, 1, 59, 476514, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.date(2020, 3, 14)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='dob',
            field=models.DateField(default=datetime.date(2020, 3, 14)),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default=datetime.time(22, 1, 59, 460171)),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default=datetime.time(22, 1, 59, 460052)),
        ),
    ]
