# Generated by Django 3.0.1 on 2019-12-22 19:02

import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0008_auto_20191222_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
        migrations.AddField(
            model_name='order',
            name='final_pair',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='final_servei',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2019, 12, 22, 19, 2, 50, 408108)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2019, 12, 22, 19, 2, 50, 393699)),
        ),
    ]
