# Generated by Django 3.0.1 on 2020-04-04 17:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0008_auto_20200404_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='data_joined',
        ),
        migrations.AddField(
            model_name='account',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 4, 4, 17, 0, 8, 332115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 4, 4, 17, 0, 8, 369861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_applied',
            field=models.DateField(default=datetime.datetime(2020, 4, 4, 17, 0, 8, 354218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_requested',
            field=models.DateField(default=datetime.datetime(2020, 4, 4, 17, 0, 8, 354136, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2020, 4, 4, 17, 0, 8, 357426, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.time(17, 0, 8, 357572)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_of_creation',
            field=models.TimeField(default=datetime.datetime(2020, 4, 4, 17, 0, 8, 357510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default=datetime.time(17, 0, 8, 350290)),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default=datetime.time(17, 0, 8, 350172)),
        ),
    ]
