# Generated by Django 3.0.1 on 2019-12-22 19:10

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0009_auto_20191222_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rejected_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2019, 12, 22, 19, 10, 10, 232528)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2019, 12, 22, 19, 10, 10, 218658)),
        ),
    ]
