# Generated by Django 3.0.1 on 2019-12-22 19:46

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0010_auto_20191222_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterCorse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(db_index=True, default='', max_length=30)),
                ('receipient', models.CharField(db_index=True, max_length=30)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='OntoNotfication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipient', models.CharField(default='', max_length=30)),
                ('receipient_token', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='', max_length=10)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2019, 12, 22, 19, 46, 2, 944818)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2019, 12, 22, 19, 46, 2, 931248)),
        ),
    ]
