# Generated by Django 3.0.1 on 2020-04-09 15:33

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0011_auto_20200407_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocieStoreSite',
            fields=[
                ('uname', models.CharField(default='', max_length=120, primary_key=True, serialize=False)),
                ('site', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 15, 33, 40, 992564, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 15, 33, 41, 180972, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_applied',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 15, 33, 41, 99208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_requested',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 15, 33, 41, 98695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 15, 33, 41, 118036, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.time(15, 33, 41, 118801)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_of_creation',
            field=models.TimeField(default=datetime.datetime(2020, 4, 9, 15, 33, 41, 118370, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.date(2020, 4, 9)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='dob',
            field=models.DateField(default=datetime.date(2020, 4, 9)),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default=datetime.time(15, 33, 41, 81529)),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default=datetime.time(15, 33, 41, 81111)),
        ),
    ]
