# Generated by Django 3.0.1 on 2019-12-22 20:08

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0012_auto_20191222_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2019, 12, 22, 20, 8, 40, 60767)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2019, 12, 22, 20, 8, 40, 45872)),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(default='', max_length=10)),
                ('address', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('dob', models.DateField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locie.Coordinates')),
            ],
        ),
    ]
