# Generated by Django 3.0.1 on 2020-05-21 23:44

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0012_auto_20200511_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servei',
            name='aadhar_image',
        ),
        migrations.RemoveField(
            model_name='servei',
            name='country',
        ),
        migrations.RemoveField(
            model_name='servei',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='servei',
            name='pan',
        ),
        migrations.RemoveField(
            model_name='servei',
            name='pan_image',
        ),
        migrations.RemoveField(
            model_name='servei',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='store',
            name='creators_profession',
        ),
        migrations.RemoveField(
            model_name='store',
            name='father_categories',
        ),
        migrations.RemoveField(
            model_name='store',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='store',
            name='product_line',
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 5, 21, 23, 44, 40, 178092, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 5, 21, 23, 44, 40, 210101, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerreviewmodel',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 23, 44, 40, 224852, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='item',
            name='required_desc',
        ),
        migrations.AddField(
            model_name='item',
            name='required_desc',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='lociestoresite',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2020, 5, 21, 23, 44, 40, 219710, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 23, 44, 40, 197431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publytics',
            name='start_dates',
            field=models.DateField(default=datetime.datetime(2020, 5, 21, 23, 44, 40, 223085, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.date(2020, 5, 21)),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default=datetime.time(23, 44, 40, 193393)),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default=datetime.time(23, 44, 40, 193289)),
        ),
    ]
