# Generated by Django 3.0.1 on 2020-04-10 06:26

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0012_auto_20200409_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='lociestoresite',
            name='site_context',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='lociestoresite',
            name='store_link',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 4, 10, 6, 26, 56, 176786, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 4, 10, 6, 26, 56, 213886, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_applied',
            field=models.DateField(default=datetime.datetime(2020, 4, 10, 6, 26, 56, 197852, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_requested',
            field=models.DateField(default=datetime.datetime(2020, 4, 10, 6, 26, 56, 197765, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2020, 4, 10, 6, 26, 56, 201244, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.time(6, 26, 56, 201376)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_of_creation',
            field=models.TimeField(default=datetime.datetime(2020, 4, 10, 6, 26, 56, 201316, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.date(2020, 4, 10)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='dob',
            field=models.DateField(default=datetime.date(2020, 4, 10)),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default=datetime.time(6, 26, 56, 194432)),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default=datetime.time(6, 26, 56, 194336)),
        ),
    ]
