# Generated by Django 3.0.1 on 2020-04-18 05:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0013_auto_20200410_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='default_item_id',
            field=models.CharField(default='none', max_length=70),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 4, 18, 5, 3, 3, 106000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 4, 18, 5, 3, 3, 143478, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_applied',
            field=models.DateField(default=datetime.datetime(2020, 4, 18, 5, 3, 3, 127547, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_requested',
            field=models.DateField(default=datetime.datetime(2020, 4, 18, 5, 3, 3, 127462, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2020, 4, 18, 5, 3, 3, 130988, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.time(5, 3, 3, 131125)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_of_creation',
            field=models.TimeField(default=datetime.datetime(2020, 4, 18, 5, 3, 3, 131064, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.date(2020, 4, 18)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='dob',
            field=models.DateField(default=datetime.date(2020, 4, 18)),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default=datetime.time(5, 3, 3, 123820)),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default=datetime.time(5, 3, 3, 123723)),
        ),
    ]
