# Generated by Django 3.0.1 on 2019-12-23 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0013_auto_20191222_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.CharField(db_index=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='officialrequest',
            name='date_applied',
            field=models.DateField(default=datetime.date(2019, 12, 23)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.TimeField(default=datetime.datetime(2019, 12, 23, 14, 59, 5, 970598)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2019, 12, 23, 14, 59, 5, 950207)),
        ),
        migrations.AlterField(
            model_name='servei',
            name='dob',
            field=models.DateField(default=datetime.date(2019, 12, 23)),
        ),
    ]
